/**
 * This file is auto-generated by idlpp
 * 
 * Source: HelloWorldData.idl
 * Generated on: 2020-02-21T11:55:38-0500
 * OpenSplice 6.10.3
 */
using DDS;
using System.Runtime.InteropServices;

namespace HelloWorldData
{
    #region Msg
    [StructLayout(LayoutKind.Sequential)]
    public sealed class Msg
    {
        public int userID;
        public string message = string.Empty;
        public double longitude_ul;
        public double lattitued_ul;
        public double longitude_lr;
        public double lattitude_lr;
    };
    #endregion

}

#region Aircraft
[StructLayout(LayoutKind.Sequential)]
public sealed class Aircraft
{
    public string tailNumber = string.Empty;
    public uint aircraftID;
};
#endregion

namespace DM
{
    #region l_WGS84
    [StructLayout(LayoutKind.Sequential)]
    public sealed class l_WGS84
    {
        public double Altitude;
        public double Latitude;
        public double Longitude;
    };
    #endregion

    #region EGI_Data
    [StructLayout(LayoutKind.Sequential)]
    public sealed class EGI_Data
    {
        public DM.l_WGS84 position = new DM.l_WGS84();
        public double time;
    };
    #endregion

    #region ATC_Data
    [StructLayout(LayoutKind.Sequential)]
    public sealed class ATC_Data
    {
        public uint aircraftID;
        public string tailNumber = string.Empty;
        public DM.l_WGS84 position = new DM.l_WGS84();
        public double time;
    };
    #endregion

    #region ATC_Function
    [StructLayout(LayoutKind.Sequential)]
    public sealed class ATC_Function
    {
        public string tailNumber = string.Empty;
        public DM.l_WGS84 position = new DM.l_WGS84();
        public double time;
        public uint aircraftID;
        public DM.EGI_Data sensor = new DM.EGI_Data();
        public Aircraft aircraft = new Aircraft();
    };
    #endregion

    #region Aircraft
    [StructLayout(LayoutKind.Sequential)]
    public sealed class Aircraft
    {
        public string tailNumber = string.Empty;
        public uint aircraftID;
    };
    #endregion

    #region Aircraft_Config
    [StructLayout(LayoutKind.Sequential)]
    public sealed class Aircraft_Config
    {
        public uint aircraftID;
        public string tailNumber = string.Empty;
    };
    #endregion

}

